### ISSUE TITLE
请问原理是宏定义吗?

### ISSUE THREAD

**Issue by nobodxbodon** [uxyheaven/yi-ios#1]
从https://github.com/uxyheaven/yi-ios/blob/master/yi/Yi.h 看来类似 https://github.com/xueyongwei/ePlus/blob/master/XYW/ViewController.m 的方法
最近在整理中文编程的资料和经验,请问能引用这个项目作为示例吗? https://nobodxbodon.github.io/program-in-chinese/

**Comment by uxyheaven** [comment]
可以

Sent from YoMail

**Comment by nobodxbodon** [comment]
谢啦! https://github.com/nobodxbodon/program-in-chinese/commit/c2da241bc6d8bf84604cda0d473faedf2ceb8808#diff-d680e8a854a7cbad6d490c445cba2eba
